name: Build_GMpro
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install Core 2.0.0
        run: |
          arduino-cli core update-index --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266@2.0.0 --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
      - name: Fix Folder Structure and Compile
        run: |
          # Membuat folder agar sesuai dengan nama file .ino
          mkdir -p GMpro
          cp GMpro.ino GMpro/GMpro.ino
          arduino-cli compile --fqbn esp8266:esp8266:d1_mini GMpro --output-dir ./out
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: GMpro-Firmware
          path: ./out/*.bin
